// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmIdO4xAdxvQ_F89l0_1sGy-2b22xH5SQ',
    appId: '1:843801937585:web:fdf5346ecad04a4d42c490',
    messagingSenderId: '843801937585',
    projectId: 'ffff-302ed',
    authDomain: 'ffff-302ed.firebaseapp.com',
    storageBucket: 'ffff-302ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZiBAYO7IylGDHof6k_nuSyW15PNQPgs',
    appId: '1:843801937585:android:7ff8f6cca85562a642c490',
    messagingSenderId: '843801937585',
    projectId: 'ffff-302ed',
    storageBucket: 'ffff-302ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZ3WpVitHfTJjjlVVvMFKH8QDY_JO0AM',
    appId: '1:843801937585:ios:e50315d8797b47e042c490',
    messagingSenderId: '843801937585',
    projectId: 'ffff-302ed',
    storageBucket: 'ffff-302ed.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsZ3WpVitHfTJjjlVVvMFKH8QDY_JO0AM',
    appId: '1:843801937585:ios:e06d47cd787163d442c490',
    messagingSenderId: '843801937585',
    projectId: 'ffff-302ed',
    storageBucket: 'ffff-302ed.appspot.com',
    iosBundleId: 'com.example.deliveryApp.RunnerTests',
  );
}
